[package]
name = "case-sensitive-replace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0"
regex = "1"
pretty_assertions = "1"
